# Generated by Django 4.1.5 on 2023-01-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='star',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='IdeaStar',
        ),
    ]
