# Generated by Django 4.1.5 on 2023-01-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('genre', models.CharField(choices=[('thriller', '스릴러'), ('fantasy', '판타지'), ('comedy', '코미디'), ('music', '음악'), ('action', '액션'), ('SF', 'SF'), ('romance', '로맨스')], max_length=20, null=True)),
                ('rating', models.FloatField()),
                ('time', models.IntegerField()),
                ('minute', models.IntegerField()),
                ('hour', models.IntegerField()),
                ('review', models.TextField()),
                ('producer', models.CharField(max_length=30)),
                ('actor', models.CharField(max_length=50)),
                ('poster', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
